#!/system/bin/sh

export DEFOPT=nosuid,nodev,noexec,noatime,context=u:object_r:sdcardfs:s0,uid=0,gid=9997,fmask=660,dmask=771,nouser_xattr

optcheck() {
    if [[ ! $(echo $1 | grep "context=") = "" ]]; then
        echo "You can't setup specific SELinux context for mounting into /storage" > /dev/stderr
        return 1
    elif [[ ! $(echo $1 | grep "uid=") = "" ]]; then
        echo "You can't setup specific UID for mounting into /storage" > /dev/stderr
        return 1                                                                            elif [[ ! $(echo $1 | grep "gid=") = "" ]]; then
        echo "You can't setup specific GID for mounting into /storage" > /dev/stderr
        return 1
    elif [[ ! $(echo $1 | grep "mask=") = "" ]]; then
        echo "You can't setup specific u/f/dmask for mounting into /storage" > /dev/stderr
        return 1
    elif [[ ! $(echo $1 | grep "user_xattr") = "" ]]; then
        echo "You can't setup xattr into /storage" > /dev/stderr
        return 1
    elif [[ ! $(echo $1 | grep "atime") = "" ]]; then
        echo "You can't setup atime into /storage" > /dev/stderr
        return 1
    elif [[ ! $(echo $1 | grep "exec") = "" ]]; then
        echo "You can't setup exec into /storage" > /dev/stderr
        return 1
    elif [[ ! $(echo $1 | grep "suid") = "" ]]; then
        echo "You can't setup suid into /storage" > /dev/stderr
        return 1
    elif [[ ! $(echo $1 | grep "dev") = "" ]]; then
        echo "You can't setup dev into /storage" > /dev/stderr
        return 1
    else
        return 0
    fi
}

help() {
	echo "Usage: sdmount-overlay -lowerdir (lowerdir1),(lowerdir2) -upperdir (upperdir1),(upperdir2) -workdir (workdir) -o (options) (mountpoint)"
	echo "(mountpoint) is /(user)/mountpoint. If your mountpoint is /0/Music, it mounts into /storage/emulated/0/Music"
}

if [[ $1 = "-lowerdir" ]]; then
    if [[ $3 = "-upperdir" ]]; then
        if [[ $5 = "-workdir" ]]; then
            if [[ $7 = "-o" ]]; then
                optcheck $8
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,upperdir=$4,workdir=$6,$DEFOPT,$8 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                su -M mount.overlay -o lowerdir=$2,upperdir=$4,workdir=$6,$DEFOPT /mnt/runtime/write/emulated$7
            fi
        elif [[ $5 = "-o" ]]; then
            if [[ $7 = "-workdir" ]]; then
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,upperdir=$4,workdir=$8,$DEFOPT,$6 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,upperdir=$4,$DEFOPT,$6 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            su -M mount.overlay -o lowerdir=$2,upperdir=$4,$DEFOPT /mnt/runtime/write/emulated$5
        fi
    elif [[ $3 = "-workdir" ]]; then
        if [[ $5 = "-upperdir" ]]; then
            if [[ $7 = "-o" ]]; then
                optcheck $8
                if [[ $? = 0 ]]; then
                     su -M mount.overlay -o lowerdir=$2,upperdir=$6,workdir=$4,$DEFOPT,$8 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                su -M mount.overlay -o lowerdir=$2,upperdir=$6,workdir=$4,$DEFOPT /mnt/runtime/write/emulated$7
            fi
        elif [[ $5 = "-o" ]]; then
            if [[ $7 = "-upperdir" ]]; then
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,upperdir=$8,workdir=$4,$DEFOPT,$6 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,workdir=$4,$DEFOPT,$6 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            su -M mount.overlay -o lowerdir=$2,workdir=$4,$DEFOPT /mnt/runtime/write/emulated$5
        fi
    elif [[ $3 = "-o" ]]; then
        if [[ $5 = "-upperdir" ]]; then
            if [[ $7 = "-workdir" ]]; then
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,upperdir=$6,workdir=$8,$DEFOPT,$4 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,upperdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        elif [[ $5 = "-workdir" ]]; then
            if [[ $7 = "-upperdir" ]]; then
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,upperdir=$8,workdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$2,workdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            optcheck $4
            if [[ $? = 0 ]]; then
                su -M mount.overlay -o lowerdir=$2,$DEFOPT,$4 /mnt/runtime/write/emulated$5
            else
                exit 1
            fi
        fi
    else
        su -M mount.overlay -o lowerdir=$2,$DEFOPT /mnt/runtime/write/emulated$3
    fi
elif [[ $1 = "-upperdir" ]]; then
    if [[ $3 = "-lowerdir" ]]; then
        if [[ $5 = "-workdir" ]]; then
            if [[ $7 = "-o" ]]; then
                optcheck $8
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,lowerdir=$4,workdir=$6,$DEFOPT,$8 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                su -M mount.overlay -o upperdir=$2,lowerdir=$4,workdir=$6,$DEFOPT /mnt/runtime/write/emulated$7
            fi
        elif [[ $5 = "-o" ]]; then
            if [[ $7 = "-workdir" ]]; then
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,lowerdir=$4,workdir=$8,$DEFOPT,$6 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,lowerdir=$4,$DEFOPT,$6 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            su -M mount.overlay -o upperdir=$2,lowerdir=$4,$DEFOPT /mnt/runtime/write/emulated$5
        fi
    elif [[ $3 = "-workdir" ]]; then
        if [[ $5 = "-lowerdir" ]]; then
            if [[ $7 = "-o" ]]; then
                optcheck $8
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,lowerdir=$6,workdir=$4,$DEFOPT,$8 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                su -M mount.overlay -o upperdir=$2,lowerdir=$6,workdir=$4,$DEFOPT /mnt/runtime/write/emulated$7
            fi
        elif [[ $5 = "-o" ]]; then
            if [[ $7 = "-lowerdir" ]]; then
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,lowerdir=$8,workdir=$4,$DEFOPT,$6 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,workdir=$4,$DEFOPT,$6 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
        fi
    elif [[ $3 = "-o" ]]; then
        if [[ $5 = "-lowerdir" ]]; then
            if [[ $7 = "-workdir" ]]; then
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,workdir=$8,lowerdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,lowerdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        elif [[ $5 = "-workdir" ]]; then
            if [[ $7 = "-lowerdir" ]]; then
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,lowerdir=$8,workdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$2,workdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            optcheck $4
            if [[ $? = 0 ]]; then
                su -M mount.overlay -o upperdir=$2,$DEFOPT,$4 /mnt/runtime/write/emulated$5
            else
                exit 1
            fi
        fi
    else
        su -M mount.overlay -o upperdir=$2,$DEFOPT /mnt/runtime/write/emulated$3
    fi
elif [[ $1 = "-workdir" ]]; then
    if [[ $3 = "-upperdir" ]]; then
        if [[ $5 = "-lowerdir" ]]; then
            if [[ $7 = "-o" ]]; then
                optcheck $8
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,upperdir=$4,lowerdir=$6,$DEFOPT,$8 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                su -M mount.overlay -o workdir=$2,upperdir=$4,lowerdir=$6,$DEFOPT /mnt/runtime/write/emulated$7
            fi
        elif [[ $5 = "-o" ]]; then
            if [[ $7 = "-lowerdir" ]]; then
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,upperdir=$4,lowerdir=$8,$DEFOPT,$6 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,upperdir=$4,$DEFOPT,$6 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
        fi
    elif [[ $3 = "-lowerdir" ]]; then
        if [[ $5 = "-upperdir" ]]; then
            if [[ $7 = "-o" ]]; then
                optcheck $8
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,lowerdir=$4,upperdir=$6,$DEFOPT,$8 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                su -M mount.overlay -o workdir=$2,lowerdir=$4,upperdir=$6,$DEFOPT /mnt/runtime/write/emulated$7
            fi
        elif [[ $5 = "-o" ]]; then
            if [[ $7 = "-upperdir" ]]; then
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,lowerdir=$4,upperdir=$8,$DEFOPT,$6 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $6
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,lowerdir=$4,$DEFOPT,$6 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            su -M mount.overlay -o workdir=$2,lowerdir=$4,$DEFOPT /mnt/runtime/write/emulated$5
        fi
    elif [[ $3 = "-o" ]]; then
        if [[ $5 = "-upperdir" ]]; then
            if [[ $7 = "-lowerdir" ]]; then
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,lowerdir=$8,upperdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,upperdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        elif [[ $5 = "-lowerdir" ]]; then
            if [[ $7 = "-upperdir" ]]; then
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,upperdir=$8,lowerdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $4
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o workdir=$2,lowerdir=$6,$DEFOPT,$4 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            optcheck $4
            if [[ $? = 0 ]]; then
                su -M mount.overlay -o workdir=$2,$DEFOPT,$4 /mnt/runtime/write/emulated$5
            else
                exit 1
            fi
        fi
    else
        su -M mount.overlay -o workdir=$2,$DEFOPT /mnt/runtime/write/emulated$3
    fi
elif [[ $1 = "-o" ]]; then
    if [[ $3 = "-workdir" ]]; then
        if [[ $5 = "-upperdir" ]]; then
            if [[ $7 = "-lowerdir" ]]; then
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$8,upperdir=$6,workdir=$4,$DEFOPT,$2 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$6,workdir=$4,$DEFOPT,$2 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        elif [[ $5 = "-lowerdir" ]]; then
            if [[ $7 = "-upperdir" ]]; then
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$8,lowerdir=$6,workdir=$4,$DEFOPT,$2 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$6,workdir=$4,$DEFOPT,$2 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            optcheck $2
            if [[ $? = 0 ]]; then
                su -M mount.overlay -o workdir=$4,$DEFOPT,$2 /mnt/runtime/write/emulated$5
            else
                exit 1
            fi
        fi
    elif [[ $3 = "-upperdir" ]]; then
        if [[ $5 = "-workdir" ]]; then
            if [[ $7 = "-lowerdir" ]]; then
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$4,workdir=$6,lowerdir=$8,$DEFOPT,$2 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$4,workdir=$6,$DEFOPT,$2 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        elif [[ $5 = "-lowerdir" ]]; then
            if [[ $7 = "-workdir" ]]; then
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$4,workdir=$8,lowerdir=$6,$DEFOPT,$2 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$4,lowerdir=$6,$DEFOPT,$2 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            optcheck $2
            if [[ $? = 0 ]]; then
                su -M mount.overlay -o upperdir=$4,$DEFOPT,$2 /mnt/runtime/write/emulated$5
            else
                exit 1
            fi
        fi
    elif [[ $3 = "-lowerdir" ]]; then
        if [[ $5 = "-workdir" ]]; then
            if [[ $7 = "-upperdir" ]]; then
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o upperdir=$8,lowerdir=$4,workdir=$6,$DEFOPT,$2 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$4,workdir=$6,$DEFOPT,$2 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        elif [[ $5 = "-upperdir" ]]; then
            if [[ $7 = "-workdir" ]]; then
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$4,upperdir=$6,workdir=$8,$DEFOPT,$2 /mnt/runtime/write/emulated$9
                else
                    exit 1
                fi
            else
                optcheck $2
                if [[ $? = 0 ]]; then
                    su -M mount.overlay -o lowerdir=$4,upperdir=$6,$DEFOPT,$2 /mnt/runtime/write/emulated$7
                else
                    exit 1
                fi
            fi
        else
            optcheck $2
            if [[ $? = 0 ]]; then
                su -M mount.overlay -o lowerdir=$4,$DEFOPT,$2 /mnt/runtime/write/emulated$5
            else
                exit 1
            fi
        fi
    else
        optcheck $2
        if [[ $? = 0 ]]; then
            help
        else
            exit 1
        fi
    fi
else
    help
fi
